'use strict';
const G=CircleGeometry,$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');
let doc=fresh(),image=null,selected=null,ci=2,view={z:1,x:0,y:0},drag=null,history=[],dirty=false,client=null,user=null,remoteId=null,busy=false,imageLoad=0;
function uid(){return globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2)}
function fresh(){return {schema:'project-adam-circle-measurements/v1',id:uid(),name:'',image:null,sets:[]}}
function msg(s){$('status').textContent=s}function set(){return doc.sets.find(s=>s.id===selected)}
function checkpoint(){history.push(JSON.stringify({name:doc.name,sets:doc.sets,selected,ci}));if(history.length>60)history.shift()}
function changed(s){dirty=true;if(s){s.success=false;s.verifiedAt=null}render()}
function dimensions(){return {w:doc.image?.width||1200,h:doc.image?.height||800}}
function fit(){const {w,h}=dimensions(),r=$('stage').getBoundingClientRect();view.z=Math.min(r.width/w,r.height/h)*.92;view.x=(r.width-w*view.z)/2;view.y=(r.height-h*view.z)/2;draw()}
function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left-view.x)/view.z,y:(e.clientY-r.top-view.y)/view.z}}
function newSet(copy){if(doc.sets.length>=200)return msg('Maximum 200 circle sets per measurement.');checkpoint();const {w,h}=dimensions();const s=copy?structuredClone(copy):{preset:'358',parentDiameter:Math.min(w,h)*.55,centers:[{x:w*.4,y:h*.5},{x:w*.5,y:h*.5},{x:w*.6,y:h*.5}],success:false,locked:false,notes:''};s.id=uid();s.name=copy?copy.name+' copy':'Set '+(doc.sets.length+1);s.success=false;s.verifiedAt=null;s.locked=false;doc.sets.push(s);selected=s.id;ci=2;changed(s)}
function render(){
 $('name').value=doc.name;$('sets').replaceChildren(...doc.sets.map(s=>new Option((s.success?'✓ ':'')+s.name,s.id)));$('sets').value=selected||'';const s=set();$('editor').hidden=!s;
 for(const id of ['duplicate','remove'])$(id).disabled=!s;
 if(s){$('setName').value=s.name;$('preset').value=s.preset;$('circle').value=ci;$('cx').value=s.centers[ci].x.toFixed(3);$('cy').value=s.centers[ci].y.toFixed(3);$('diameter').value=G.diameter(s,ci).toFixed(3);$('scale').max=Math.max(dimensions().w*2,s.parentDiameter*1.1);$('scale').value=s.parentDiameter;$('success').checked=!!s.success;$('locked').checked=!!s.locked;$('notes').value=s.notes||'';for(const id of ['cx','cy','diameter','scale','preset'])$(id).disabled=!!s.locked;}
 $('undo').disabled=!history.length;$('measurements').replaceChildren();for(const s of doc.sets)for(let i=0;i<3;i++){const tr=document.createElement('tr');for(const v of [s.name,G.ratios(s.preset).join(' : '),['Small','Middle','Parent'][i],s.centers[i].x.toFixed(3),s.centers[i].y.toFixed(3),G.diameter(s,i).toFixed(3),(G.diameter(s,i)/2).toFixed(3),s.success?'Successful':'Unchecked']){const td=document.createElement('td');td.textContent=v;tr.append(td)}$('measurements').append(tr)}
 $('imageInfo').textContent=doc.image?`${doc.image.name} · ${doc.image.width} × ${doc.image.height} original pixels`:'No image loaded. Load or paste an image before recording a fit.';draw();
}
function circles(c,z=1,ox=0,oy=0,exporting=false){const colors=['#ffc96b','#f393d7','#54dfdf'];for(const s of doc.sets)for(let i=0;i<3;i++){const p=s.centers[i],x=ox+p.x*z,y=oy+p.y*z,r=G.diameter(s,i)*z/2;c.strokeStyle=colors[i];c.globalAlpha=s.id===selected||exporting?1:.55;c.lineWidth=(s.id===selected&&i===ci?2.5:1.5);c.beginPath();c.arc(x,y,r,0,2*Math.PI);c.stroke();c.beginPath();c.moveTo(x-7,y);c.lineTo(x+7,y);c.moveTo(x,y-7);c.lineTo(x,y+7);c.stroke();c.fillStyle=colors[i];c.font='12px system-ui';c.fillText(`${s.name} · ${G.ratios(s.preset)[i]}${i===2?' parent':''}`,x+10,y-10);if(!exporting&&s.id===selected&&i===ci){c.fillRect(x+r-4,y-4,8,8)}}c.globalAlpha=1}
function draw(){const r=$('stage').getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);if(image)ctx.drawImage(image,view.x,view.y,doc.image.width*view.z,doc.image.height*view.z);else{ctx.fillStyle='#a6c2d2';ctx.font='16px system-ui';ctx.fillText('Load or paste a screenshot to begin',25,35)}circles(ctx,view.z,view.x,view.y)}
function zoom(f,x,y){const z=Math.min(30,Math.max(.02,view.z*f));view.x=x-(x-view.x)*z/view.z;view.y=y-(y-view.y)*z/view.z;view.z=z;draw()}
canvas.addEventListener('wheel',e=>{e.preventDefault();const r=canvas.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.001),e.clientX-r.left,e.clientY-r.top)},{passive:false});
canvas.onpointerdown=e=>{const p=point(e);let hit=null,best=Infinity;for(const s of doc.sets)for(let i=0;i<3;i++){const d=Math.hypot(p.x-s.centers[i].x,p.y-s.centers[i].y)*view.z,edge=Math.abs(d-G.diameter(s,i)*view.z/2),distance=Math.min(d,edge);if(distance<12&&distance<best){best=distance;hit={s,i,mode:d<edge?'move':'resize'}}}if(hit){selected=hit.s.id;ci=hit.i;if(hit.s.locked){render();msg('This set is locked. Unlock it to adjust.');return}checkpoint();drag={...hit,start:p,centers:structuredClone(hit.s.centers),diameter:hit.s.parentDiameter};render()}else drag={mode:'pan',x:e.clientX,y:e.clientY,vx:view.x,vy:view.y};canvas.setPointerCapture(e.pointerId)};
canvas.onpointermove=e=>{if(!drag)return;if(drag.mode==='pan'){view.x=drag.vx+e.clientX-drag.x;view.y=drag.vy+e.clientY-drag.y;draw();return}const p=point(e),s=drag.s;if(drag.mode==='resize'){const c=s.centers[ci];G.resize(s,ci,Math.max(.01,Math.hypot(p.x-c.x,p.y-c.y)*2))}else{const dx=p.x-drag.start.x,dy=p.y-drag.start.y;for(let i=0;i<3;i++)if(i===ci||$('whole').checked)s.centers[i]={x:drag.centers[i].x+dx,y:drag.centers[i].y+dy}}changed(s)};
canvas.onpointerup=canvas.onpointercancel=()=>drag=null;
$('preset').replaceChildren(...G.presets.map(p=>new Option(G.ratios(p).join(' : '),p)));$('preset').onchange=()=>{const s=set();checkpoint();G.changePreset(s,$('preset').value);changed(s)};
$('sets').onchange=()=>{selected=$('sets').value;render()};$('circle').onchange=()=>{ci=+$('circle').value;render()};$('add').onclick=()=>newSet();$('duplicate').onclick=()=>newSet(set());$('remove').onclick=()=>{checkpoint();doc.sets=doc.sets.filter(s=>s.id!==selected);selected=doc.sets[0]?.id;changed()};
for(const id of ['cx','cy','diameter'])$(id).onchange=()=>{const s=set(),v=Number($(id).value);if(!Number.isFinite(v)||(id==='diameter'&&v<=0)){render();return}checkpoint();if(id==='diameter')G.resize(s,ci,v);else s.centers[ci][id==='cx'?'x':'y']=v;changed(s)};
$('scale').onpointerdown=()=>checkpoint();$('scale').onkeydown=e=>{if(e.key.startsWith('Arrow'))checkpoint()};$('scale').oninput=()=>{const s=set();s.parentDiameter=+$('scale').value;changed(s)};
$('name').onchange=()=>{checkpoint();doc.name=$('name').value;dirty=true};$('setName').onchange=()=>{checkpoint();set().name=$('setName').value||'Unnamed set';dirty=true;render()};$('notes').onchange=()=>{checkpoint();set().notes=$('notes').value;dirty=true};$('success').onchange=()=>{if(!image){msg('Load an image before marking a successful fit.');render();return}checkpoint();set().success=$('success').checked;set().verifiedAt=set().success?new Date().toISOString():null;dirty=true;render()};$('locked').onchange=()=>{checkpoint();set().locked=$('locked').checked;dirty=true;render()};
$('undo').onclick=()=>{const h=JSON.parse(history.pop());doc.name=h.name;doc.sets=h.sets;selected=h.selected;ci=h.ci;dirty=true;render()};
window.addEventListener('keydown',e=>{if(busy)return;if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||!set()||set().locked)return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!d)return;e.preventDefault();checkpoint();const n=e.shiftKey?10:1;for(let i=0;i<3;i++)if(i===ci||$('whole').checked){set().centers[i].x+=d[0]*n;set().centers[i].y+=d[1]*n}changed(set())});
function blobURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}function decode(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(Error('Cannot decode image'));im.src=src})}
async function loadImage(file){if(busy)return;const originalDoc=doc,loadId=++imageLoad;try{if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type))throw Error('Use PNG, JPEG or WebP.');const dataUrl=await blobURL(file),im=await decode(dataUrl);if(busy||doc!==originalDoc||loadId!==imageLoad)return;if(doc.sets.length&&!confirm('Replace the source image and keep circle coordinates unchanged? All successful-fit marks will be cleared.'))return;doc.image={name:file.name||'Pasted image',width:im.naturalWidth,height:im.naturalHeight,dataUrl};image=im;doc.sets.forEach(s=>{s.success=false;s.verifiedAt=null});history=[];dirty=true;render();fit();msg('Image loaded at original resolution.')}catch(e){msg(e.message)}}
$('imageFile').onchange=e=>{loadImage(e.target.files[0]);e.target.value=''};window.addEventListener('paste',e=>{const it=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(it){e.preventDefault();loadImage(it.getAsFile())}});
function payload(){return {...structuredClone(doc),updatedAt:new Date().toISOString(),coordinateSystem:{units:'original-image-pixels',origin:'top-left',x:'right',y:'down',circleMeasure:'diameter',parent:'largest ratio / index 2'},sets:doc.sets.map(s=>({...structuredClone(s),measurements:s.centers.map((c,i)=>({...c,ratio:G.ratios(s.preset)[i],diameter:G.diameter(s,i),radius:G.diameter(s,i)/2}))}))}}
function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function filename(){return (doc.name||'circle-measurements').replace(/[^\w.-]+/g,'_')}
$('download').onclick=()=>{saveBlob(new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'}),filename()+'.json');dirty=false;msg('JSON exported with source image and exact coordinates.')};
$('csv').onclick=()=>{const esc=v=>'"'+String(v).replaceAll('"','""')+'"';const rows=[['measurement','set','preset','circle','ratio','x_px','y_px','diameter_px','radius_px','successful','notes']];for(const s of doc.sets)for(let i=0;i<3;i++)rows.push([doc.name,s.name,s.preset,i+1,G.ratios(s.preset)[i],s.centers[i].x,s.centers[i].y,G.diameter(s,i),G.diameter(s,i)/2,!!s.success,s.notes||'']);saveBlob(new Blob([rows.map(r=>r.map(esc).join(',')).join('\n')],{type:'text/csv'}),filename()+'.csv')};
async function apply(data){G.validate(data);const im=data.image?await decode(data.image.dataUrl):null;if(im&&(im.naturalWidth!==data.image.width||im.naturalHeight!==data.image.height))throw Error('Image dimensions do not match saved metadata');doc=structuredClone(data);image=im;selected=doc.sets[0]?.id;history=[];dirty=false;render();fit()}
function discard(){return !dirty||confirm('Discard unsaved changes? Export JSON first if you want to keep them.')}
$('jsonFile').onchange=async e=>{if(busy)return;await task(async()=>{try{const file=e.target.files[0];if(file&&discard()){await apply(JSON.parse(await file.text()));remoteId=null;msg('Imported circles and source image. Next upload creates a new saved record.')}}catch(err){msg(err.message)}e.target.value=''});};
$('new').onclick=()=>{if(discard()){doc=fresh();image=null;selected=null;remoteId=null;history=[];dirty=false;render();fit()}};
$('png').onclick=()=>{if(!image)return msg('Load an image first.');const c=document.createElement('canvas');c.width=doc.image.width;c.height=doc.image.height;const x=c.getContext('2d');x.drawImage(image,0,0);circles(x,1,0,0,true);c.toBlob(b=>saveBlob(b,filename()+'_annotated.png'))};$('fit').onclick=fit;$('plus').onclick=()=>zoom(1.25,canvas.clientWidth/2,canvas.clientHeight/2);$('minus').onclick=()=>zoom(.8,canvas.clientWidth/2,canvas.clientHeight/2);new ResizeObserver(draw).observe($('stage'));window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
async function connect(){if(client)return client;const [{createClient},cfg]=await Promise.all([import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'),import('../project-adam-config.js')]);if(!cfg.SUPABASE_URL||!cfg.SUPABASE_PUBLISHABLE_KEY)throw Error('Parent project-adam-config.js must export SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY');client=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY);client.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;$('auth').textContent=user?'Signed in as '+user.email:'Not signed in.';if(!user){remoteId=null;$('saved').replaceChildren()}});const {data,error}=await client.auth.getUser();if(error&&error.name!=='AuthSessionMissingError')msg(error.message);user=data?.user||null;return client}
async function task(fn){if(busy)return;busy=true;document.body.inert=true;drag=null;msg('Working…');for(const id of ['login','logout','upload','refresh','load'])$(id).disabled=true;try{await fn()}catch(e){msg(e.message+'\nIf the table is missing, run schema.sql in Supabase.')}finally{busy=false;document.body.inert=false;for(const id of ['login','logout','upload','refresh','load'])$(id).disabled=false}}
async function requireUser(){await connect();if(!user)throw Error('Sign in first.');return client}
async function list(){await requireUser();const {data,error}=await client.from('circle_measurements').select('id,name,updated_at').order('updated_at',{ascending:false}).limit(500);if(error)throw error;$('saved').replaceChildren(...data.map(r=>new Option(r.name+' · '+new Date(r.updated_at).toLocaleString(),r.id)));if(remoteId)$('saved').value=remoteId;msg(data.length+' saved measurements loaded (up to 500).')}
$('login').onclick=()=>task(async()=>{await connect();const {error}=await client.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)throw error;$('password').value='';const r=await client.auth.getUser();user=r.data.user;await list()});$('logout').onclick=()=>task(async()=>{await connect();const {error}=await client.auth.signOut();if(error)throw error;msg('Signed out.')});$('refresh').onclick=()=>task(list);
$('upload').onclick=()=>task(async()=>{await requireUser();doc.name=$('name').value.trim();if(!doc.name)throw Error('Name the measurement first.');if(!image||!doc.sets.length)throw Error('Add a source image and at least one circle set.');const snapshot=payload(),before=JSON.stringify(doc),id=remoteId||uid();const {error}=await client.from('circle_measurements').upsert({id,owner_id:user.id,name:doc.name,payload:snapshot,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)throw error;remoteId=id;if(JSON.stringify(doc)===before)dirty=false;await list();msg('Uploaded circles, fit notes and original image. '+(dirty?'Newer edits remain unsaved.':''))});
$('load').onclick=()=>task(async()=>{if(!discard())return;await requireUser();const id=$('saved').value;if(!id)throw Error('Select a saved measurement.');const {data,error}=await client.from('circle_measurements').select('payload').eq('id',id).single();if(error)throw error;await apply(data.payload);remoteId=id;msg('Loaded measurement and source image. Upload will update this record.')});
render();fit();
